---
- name: Continuous Lab Saturation Source
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - http://13.62.54.18:8000  # Or any internal/external URL
        delay: 1                 # Polls every 1 second to maximize traffic
  rules:
    - name: Handle HTTP Up State
      condition: event.url_check.status == "up"
      action:
        run_playbook:
          name: print_event.yml
