---
- name: Hello World Test for Linux
  hosts: all
  gather_facts: yes
  vars:
    myvar: "Banana" 
  tasks:
    - name: Say Hello
      ansible.builtin.debug:
        msg: "Hello from Linux EC2! Connection successful. {{ myvar }}"
