---
- name: Continuous Lab Saturation Source
  hosts: all
  sources:
    - ansible.eda.url_check:
        urls:
          - "http://13.62.64.189:8000"
        delay: 1
  rules:
    - name: Catch Every Single Ping
      condition: event.url_check is defined  # <--- Fires on absolutely any response
      action:
        debug:
          msg: "Boom! We hooked an event from AWS!"
